### ISSUE TITLE
Redis rdb save crashes if no samples yet

### ISSUE THREAD

**Issue by someburner** [danni-m/redis-timeseries#15]
I actually added a fix locally and didn't have time to PR. But looking over my fix, I'm not sure it's totally correct. From what I remember, the problem is redis will crash when trying to save to rdb if there are no samples yet. I discovered it by setting my `redis.conf` to save every minute, regardless of changes to keyspace, in order to test a backup copying cron job. I traced it down the function below, and seen is my go at fixing. This does seem to work, but not sure about the if-else logic.

```c
 Sample *SeriesItertorGetNext(SeriesItertor *iterator) {
     while (iterator->currentChunk != NULL)
     {
        Chunk *currentChunk = iterator->currentChunk;
 -      if (ChunkGetLastSample(currentChunk)->timestamp < iterator->minTimestamp)
 +      Sample * lastSample = ChunkGetLastSample(currentChunk);
 +      if ( !lastSample )
 +         return NULL;
 +
 +      if (lastSample->timestamp < iterator->minTimestamp)
        {
           iterator->currentChunk = currentChunk->nextChunk;
           iterator->chunkIterator = NewChunkIterator(iterator->currentChunk);
           continue;
        }
 -      else if (ChunkGetFirstSample(currentChunk)->timestamp > iterator->maxTimestamp)
 +      else if ( (ChunkGetFirstSample(currentChunk)) &&
 +            ChunkGetFirstSample(currentChunk)->timestamp > iterator->maxTimestamp)
        {
           break;
        }
```

**Comment by danni-m** [comment]
@someburner thanks. fixed it, also added a test case for empty time series with a `DUMP` command.
