### ISSUE TITLE
Add NX argument to TS.CREATE

### ISSUE THREAD

**Issue by tazimmerman** [danni-m/redis-timeseries#29]
Hi,

What are your thoughts on adding a NX (or similar) argument to TS.CREATE that will only create a new TS key if it doesn't already exist? This way if a process is restarted, it doesn't have to query Redis to determine what TS keys exist or not, and instead will issue a TS.CREATE for any update. For some use cases the extra command in a pipeline might not be acceptable, but for lower-throughput uses the overhead is not measurable.

Thanks,
Troy

**Comment by danni-m** [comment]
Sounds reasonable.
You can also acheive that already using global configuration, when you call the module with the retention policy:
`loadmodule ./src/redis-tsdb-module.so ETNTION_POLICY 3500`

And this configuration will load the module with automatic compactions:
`loadmodule ./src/redis-tsdb-module.so COMPACTION_POLICY max:1m:1d;min:10s:1h;avg:2h:10d;avg:3d:100d RETNTION_POLICY 3500`

This will allow the module to create the keys automatically with the preconfigured settings.

**Comment by tazimmerman** [comment]
The global configuration approach is perfect for my needs. It never dawned on me to explore it. Thank you!

**Comment by tazimmerman** [comment]
In config.c, if you load the module with only a retention policy (no default compaction policy), the TSGlobalConfig.hasGlobalConfig variable is never set to TRUE.

**Comment by danni-m** [comment]
@tazimmerman Pushed a fixed, please reopen if you still have issues.
