### ISSUE TITLE
Redis crashes when bucket size in aggregated query is 0

### ISSUE THREAD

**Issue by danni-m** [danni-m/redis-timeseries#7]

**Comment by someburner** [comment]
Think it's due to the % 0 that occurs. See [here](https://github.com/someburner/redis-timeseries/commit/186e0b116be21a1acf47e116fb7a2f4c6ba500ec)

**Comment by danni-m** [comment]
@someburner you are right, can you create a PR for that, looks like an easy merge.

**Comment by danni-m** [comment]
@someburner thanks!
